version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mindlog_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: mindlog
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: